/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BilibiliSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/bilibili-client.ts
var import_obsidian = require("obsidian");
var BilibiliClient = class {
  constructor() {
    this.headers = {
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
      "Accept-Language": "zh-CN,zh;q=0.9",
      "Referer": "https://www.bilibili.com/"
    };
  }
  async resolveTarget(rawUrl) {
    var _a, _b, _c;
    const finalUrl = await this.followShortUrl(rawUrl.trim());
    const parsed = new URL(finalUrl);
    if (parsed.hostname === "space.bilibili.com") {
      const match = parsed.pathname.match(/\/(\d+)/);
      if (!match) {
        throw new Error("\u65E0\u6CD5\u4ECE UP \u4E3B\u9875\u94FE\u63A5\u4E2D\u89E3\u6790 mid\u3002");
      }
      const mid = match[1];
      const listMatch = parsed.pathname.match(/\/lists\/(\d+)/);
      const listType = parsed.searchParams.get("type") || "";
      if (listMatch && (listType === "season" || listType === "series")) {
        const listId = listMatch[1];
        return this.resolveCollectionTarget(mid, listId, listType);
      }
      const initial = await this.fetchListInitialState(mid);
      const upName = ((_b = (_a = initial == null ? void 0 : initial.mediaListInfo) == null ? void 0 : _a.upper) == null ? void 0 : _b.name) || ((_c = initial == null ? void 0 : initial.mediaListInfo) == null ? void 0 : _c.title) || mid;
      const upUrl = `https://space.bilibili.com/${mid}/upload/video`;
      return {
        source_type: "up",
        source_id: mid,
        mid,
        up_name: upName,
        title: upName,
        source_url: upUrl,
        source_key: `up:${mid}`
      };
    }
    if (parsed.hostname === "www.bilibili.com" && parsed.pathname.includes("/video/")) {
      const bvidMatch = parsed.pathname.match(/\/video\/(BV[0-9A-Za-z]+)/);
      if (!bvidMatch) {
        throw new Error("\u65E0\u6CD5\u4ECE\u89C6\u9891\u94FE\u63A5\u4E2D\u89E3\u6790 BV \u53F7\u3002");
      }
      const up = await this.resolveUpFromBvid(bvidMatch[1]);
      return {
        source_type: "up",
        source_id: up.mid,
        mid: up.mid,
        up_name: up.up_name,
        title: up.up_name,
        source_url: up.up_url,
        source_key: `up:${up.mid}`
      };
    }
    throw new Error("\u4EC5\u652F\u6301 B \u7AD9 UP \u4E3B\u9875\u94FE\u63A5\u3001\u6295\u7A3F\u9875\u94FE\u63A5\u6216\u89C6\u9891\u94FE\u63A5\u3002");
  }
  async resolveCollectionTarget(mid, listId, listType) {
    var _a, _b;
    if (listType === "season") {
      const meta2 = await this.fetchSeasonPage(listId, 1, 1);
      const info = meta2.info || {};
      const upName2 = (info.upper || {}).name || mid;
      const title2 = info.title || `season-${listId}`;
      return {
        source_type: "season",
        source_id: listId,
        mid,
        up_name: upName2,
        title: title2,
        source_url: `https://space.bilibili.com/${mid}/lists/${listId}?type=season`,
        source_key: `season:${listId}`
      };
    }
    const meta = await this.fetchSeriesMeta(listId);
    const upName = (meta.meta || {}).name || mid;
    const title = ((_a = meta.meta) == null ? void 0 : _a.title) || `series-${listId}`;
    const ownerMid = String(((_b = meta.meta) == null ? void 0 : _b.mid) || mid);
    return {
      source_type: "series",
      source_id: listId,
      mid: ownerMid,
      up_name: upName,
      title,
      source_url: `https://space.bilibili.com/${ownerMid}/lists/${listId}?type=series`,
      source_key: `series:${listId}`
    };
  }
  async resolveUpFromBvid(bvid) {
    var _a;
    const payload = await this.getJson(
      "https://api.bilibili.com/x/web-interface/view",
      { bvid },
      "https://www.bilibili.com/"
    );
    const owner = ((_a = payload.data) == null ? void 0 : _a.owner) || {};
    const mid = String(owner.mid || "");
    const upName = owner.name || mid;
    if (!mid) {
      throw new Error("\u89C6\u9891\u8BE6\u60C5\u91CC\u6CA1\u6709\u627E\u5230\u6240\u5C5E UP \u4E3B\u3002");
    }
    return {
      mid,
      up_name: upName,
      up_url: `https://space.bilibili.com/${mid}/upload/video`
    };
  }
  async fetchTargetVideos(target) {
    if (target.source_type === "up") {
      const { upName, videos, collections } = await this.fetchAllUploadVideos(target.mid);
      target.up_name = upName || target.up_name;
      target.title = target.up_name;
      return { target, videos, collections };
    }
    if (target.source_type === "season") {
      const videos = await this.fetchAllSeasonVideos(target.source_id);
      return { target, videos, collections: [] };
    }
    if (target.source_type === "series") {
      const videos = await this.fetchAllSeriesVideos(target.mid, target.source_id);
      return { target, videos, collections: [] };
    }
    throw new Error(`\u6682\u4E0D\u652F\u6301\u7684\u5BFC\u5165\u7C7B\u578B\uFF1A${target.source_type}`);
  }
  async fetchAllUploadVideos(mid) {
    const initial = await this.fetchListInitialState(mid);
    const mediaInfo = (initial == null ? void 0 : initial.mediaListInfo) || {};
    const upName = ((mediaInfo.upper || {}).name || mediaInfo.title || mid).trim();
    const total = parseInt((initial == null ? void 0 : initial.listTotal) || mediaInfo.media_count || "0");
    const seedList = (initial == null ? void 0 : initial.resourceList) || [];
    if (!seedList.length) {
      throw new Error("\u672A\u4ECE\u5217\u8868\u9875\u8BFB\u53D6\u5230\u516C\u5F00\u89C6\u9891\u5217\u8868\u3002");
    }
    const firstSeed = seedList[0];
    const currentBatch = await this.fetchUploadBatchWithCurrent(mid, firstSeed.bvid, firstSeed.oid);
    const seen = /* @__PURE__ */ new Map();
    for (const item of currentBatch) {
      seen.set(item.bvid, item);
    }
    let cursor = currentBatch[currentBatch.length - 1];
    while (cursor && seen.size < total) {
      const { batch, hasMore } = await this.fetchUploadBatch(mid, cursor.bvid, cursor.oid);
      const fresh = batch.filter((item) => !seen.has(item.bvid));
      if (!fresh.length)
        break;
      for (const item of fresh) {
        seen.set(item.bvid, item);
      }
      cursor = fresh[fresh.length - 1];
      if (!hasMore)
        break;
    }
    const videos = Array.from(seen.values()).sort((a, b) => {
      const dateDiff = b.pubdate - a.pubdate;
      return dateDiff !== 0 ? dateDiff : b.bvid.localeCompare(a.bvid);
    });
    const collections = await this.fetchCollectionsMeta(mid);
    return { upName, videos, collections };
  }
  async fetchUploadBatchWithCurrent(mid, cursorBvid, cursorOid) {
    const params = new URLSearchParams({
      mobi_app: "web",
      type: "1",
      biz_id: mid,
      ps: "20",
      desc: "true",
      sort_field: "1",
      tid: "0",
      bvid: cursorBvid,
      oid: String(cursorOid),
      otype: "2",
      with_current: "true",
      direction: "false",
      preview: "0"
    });
    const payload = await this.getJson(
      `https://api.bilibili.com/x/v2/medialist/resource/list?${params.toString()}`,
      void 0,
      `https://www.bilibili.com/list/${mid}?sort_field=pubdate`
    );
    const data = payload.data || {};
    return (data.media_list || []).map(this.normalizeMediaListItem);
  }
  async fetchUploadBatch(mid, cursorBvid, cursorOid) {
    const params = new URLSearchParams({
      mobi_app: "web",
      type: "1",
      biz_id: mid,
      ps: "20",
      desc: "true",
      sort_field: "1",
      tid: "0",
      bvid: cursorBvid,
      oid: String(cursorOid),
      otype: "2",
      with_current: "false",
      direction: "false",
      preview: "0"
    });
    const payload = await this.getJson(
      `https://api.bilibili.com/x/v2/medialist/resource/list?${params.toString()}`,
      void 0,
      `https://www.bilibili.com/list/${mid}?sort_field=pubdate`
    );
    const data = payload.data || {};
    const batch = (data.media_list || []).map(this.normalizeMediaListItem);
    return { batch, hasMore: Boolean(data.has_more) };
  }
  async fetchCollectionsMeta(mid) {
    var _a;
    const params = new URLSearchParams({
      mid,
      page_num: "1",
      page_size: "20"
    });
    const payload = await this.getJson(
      `https://api.bilibili.com/x/polymer/web-space/seasons_series_list?${params.toString()}`,
      void 0,
      `https://space.bilibili.com/${mid}/upload/video`
    );
    const data = ((_a = payload.data) == null ? void 0 : _a.items_lists) || {};
    const collections = [];
    for (const season of data.seasons_list || []) {
      const meta = season.meta || {};
      const title = meta.title || meta.name;
      if (!title)
        continue;
      collections.push({
        title,
        season_id: String(meta.season_id || ""),
        total: parseInt(meta.total || "0")
      });
    }
    for (const series of data.series_list || []) {
      const meta = series.meta || {};
      const title = meta.title || meta.name;
      if (!title)
        continue;
      collections.push({
        title,
        series_id: String(meta.series_id || ""),
        total: parseInt(meta.total || "0")
      });
    }
    return collections;
  }
  async fetchSeasonPage(seasonId, pn, ps) {
    const params = new URLSearchParams({
      season_id: seasonId,
      pn: String(pn),
      ps: String(ps)
    });
    const payload = await this.getJson(
      `https://api.bilibili.com/x/space/fav/season/list?${params.toString()}`,
      void 0,
      "https://www.bilibili.com/"
    );
    return payload.data || {};
  }
  async fetchAllSeasonVideos(seasonId) {
    const firstPage = await this.fetchSeasonPage(seasonId, 1, 20);
    const info = firstPage.info || {};
    const total = parseInt(info.media_count || "0");
    const videos = (firstPage.medias || []).map(this.normalizeSeasonMedia);
    const seen = /* @__PURE__ */ new Map();
    for (const item of videos) {
      seen.set(item.bvid, item);
    }
    const totalPages = Math.max(1, Math.ceil(total / 20));
    for (let pn = 2; pn <= totalPages; pn++) {
      const page = await this.fetchSeasonPage(seasonId, pn, 20);
      for (const item of page.medias || []) {
        const normalized = this.normalizeSeasonMedia(item);
        if (!seen.has(normalized.bvid)) {
          seen.set(normalized.bvid, normalized);
        }
      }
    }
    return Array.from(seen.values()).sort((a, b) => {
      const dateDiff = b.pubdate - a.pubdate;
      return dateDiff !== 0 ? dateDiff : b.bvid.localeCompare(a.bvid);
    });
  }
  async fetchSeriesMeta(seriesId) {
    const params = new URLSearchParams({
      series_id: seriesId
    });
    const payload = await this.getJson(
      `https://api.bilibili.com/x/series/series?${params.toString()}`,
      void 0,
      "https://www.bilibili.com/"
    );
    return payload.data || {};
  }
  async fetchAllSeriesVideos(mid, seriesId) {
    var _a, _b;
    const meta = await this.fetchSeriesMeta(seriesId);
    const total = parseInt(((_a = meta.meta) == null ? void 0 : _a.total) || "0");
    const seen = /* @__PURE__ */ new Map();
    const totalPages = Math.max(1, Math.ceil(total / 20));
    for (let pn = 1; pn <= totalPages; pn++) {
      const params = new URLSearchParams({
        mid,
        series_id: seriesId,
        only_normal: "true",
        sort: "desc",
        pn: String(pn),
        ps: "20"
      });
      const payload = await this.getJson(
        `https://api.bilibili.com/x/series/archives?${params.toString()}`,
        void 0,
        "https://www.bilibili.com/"
      );
      for (const item of ((_b = payload.data) == null ? void 0 : _b.archives) || []) {
        const normalized = this.normalizeSeriesArchive(item);
        if (!seen.has(normalized.bvid)) {
          seen.set(normalized.bvid, normalized);
        }
      }
    }
    return Array.from(seen.values()).sort((a, b) => {
      const dateDiff = b.pubdate - a.pubdate;
      return dateDiff !== 0 ? dateDiff : b.bvid.localeCompare(a.bvid);
    });
  }
  async followShortUrl(rawUrl) {
    if (!rawUrl) {
      throw new Error("\u8BF7\u8F93\u5165 B \u7AD9\u94FE\u63A5\u3002");
    }
    if (rawUrl.includes("b23.tv")) {
      const response = await (0, import_obsidian.requestUrl)({
        url: rawUrl,
        method: "GET",
        headers: this.headers
      });
      return response.url || rawUrl;
    }
    return rawUrl;
  }
  async fetchListInitialState(mid) {
    const url = `https://www.bilibili.com/list/${mid}?sort_field=pubdate`;
    const html = await this.getText(url, "https://www.bilibili.com/");
    const match = html.match(/__INITIAL_STATE__\s*=\s*({.*?});\s*\(function/s);
    if (!match) {
      throw new Error("\u672A\u80FD\u4ECE B \u7AD9\u5217\u8868\u9875\u89E3\u6790\u51FA\u521D\u59CB\u6570\u636E\u3002");
    }
    try {
      return JSON.parse(match[1]);
    } catch (e) {
      throw new Error("\u89E3\u6790 B \u7AD9\u5217\u8868\u9875\u521D\u59CB\u6570\u636E\u5931\u8D25\u3002");
    }
  }
  async getText(url, referer) {
    const headers = { ...this.headers };
    if (referer) {
      headers.Referer = referer;
    }
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: "GET",
      headers
    });
    return response.text;
  }
  normalizeMediaListItem(item) {
    var _a;
    const bvid = item.bv_id || item.bvid;
    const oid = parseInt(item.id || item.aid || "0");
    return {
      bvid,
      oid,
      title: item.title || "",
      url: `https://www.bilibili.com/video/${bvid}`,
      pubdate: parseInt(item.pubtime || "0"),
      duration_seconds: parseInt(item.duration || "0"),
      view_count: parseInt(((_a = item.cnt_info) == null ? void 0 : _a.play) || "0"),
      source_kind: "upload"
    };
  }
  normalizeSeasonMedia(item) {
    var _a;
    const bvid = item.bvid;
    const aid = parseInt(item.id || item.aid || "0");
    return {
      bvid,
      oid: aid,
      title: item.title || "",
      url: `https://www.bilibili.com/video/${bvid}`,
      pubdate: parseInt(item.pubtime || item.pubdate || "0"),
      duration_seconds: parseInt(item.duration || "0"),
      view_count: parseInt(((_a = item.cnt_info) == null ? void 0 : _a.play) || "0"),
      source_kind: "season"
    };
  }
  normalizeSeriesArchive(item) {
    var _a;
    const bvid = item.bvid;
    const aid = parseInt(item.aid || "0");
    return {
      bvid,
      oid: aid,
      title: item.title || "",
      url: `https://www.bilibili.com/video/${bvid}`,
      pubdate: parseInt(item.pubdate || "0"),
      duration_seconds: parseInt(item.duration || "0"),
      view_count: parseInt(((_a = item.stat) == null ? void 0 : _a.view) || "0"),
      source_kind: "series"
    };
  }
  async getJson(url, params, referer) {
    let finalUrl = url;
    if (params) {
      const searchParams = new URLSearchParams(params);
      finalUrl += (url.includes("?") ? "&" : "?") + searchParams.toString();
    }
    const headers = { ...this.headers };
    if (referer) {
      headers.Referer = referer;
    }
    const response = await (0, import_obsidian.requestUrl)({
      url: finalUrl,
      method: "GET",
      headers
    });
    const data = response.json;
    const code = data.code || 0;
    if (code !== 0) {
      throw new Error(data.message || `B\u7AD9\u63A5\u53E3\u8FD4\u56DE\u5F02\u5E38 code=${code}`);
    }
    return data;
  }
};

// src/obsidian-writer.ts
var import_obsidian2 = require("obsidian");
function safeFileName(value) {
  const cleaned = value.replace(/[\\/:*?"<>|]+/g, "_").trim();
  return cleaned.substring(0, 120) || "\u672A\u547D\u540DUP\u4E3B";
}
function escapeMdCell(value) {
  return String(value).replace(/\|/g, "\\|").replace(/\n/g, " ").trim();
}
function formatPubdate(pubdate) {
  if (!pubdate || pubdate <= 0)
    return "";
  const date = new Date(pubdate * 1e3);
  return date.toISOString().split("T")[0];
}
var ObsidianWriter = class {
  constructor(vault, indexNoteName) {
    this.vault = vault;
    this.indexNoteName = indexNoteName;
  }
  notePathFor(sourceType, title, sourceId, categoryRel) {
    const prefix = { up: "B\u7AD9UP", season: "B\u7AD9\u5408\u96C6", series: "B\u7AD9\u7CFB\u5217" }[sourceType] || "B\u7AD9";
    const basePath = categoryRel ? `${categoryRel}/` : "";
    return `${basePath}${safeFileName(prefix)}-${safeFileName(title)}-${safeFileName(sourceId)}-\u89C6\u9891\u5217\u8868.md`;
  }
  async writeChannelNote(notePath, title, upName, mid, sourceUrl, videos, collections, categoryRel, sourceType) {
    const syncedAt = (/* @__PURE__ */ new Date()).toISOString().replace("T", " ").substring(0, 19);
    const lines = [
      `# B\u7AD9 UP \u89C6\u9891\u5217\u8868 - ${title}`,
      "",
      `- UP\u4E3B\uFF1A${upName}`,
      `- MID\uFF1A${mid}`,
      `- \u6765\u6E90\uFF1A${sourceUrl}`,
      `- \u89C6\u9891\u6570\uFF1A${videos.length}`,
      `- \u91C7\u96C6\u65F6\u95F4\uFF1A${syncedAt}`
    ];
    if (collections.length > 0) {
      const names = collections.map((item) => item.title).join("\u3001");
      lines.push(`- \u5408\u96C6\u4FE1\u606F\uFF1A${names}`);
    }
    lines.push(
      "",
      "|  \u5E8F\u53F7 | \u6807\u9898 | \u5730\u5740 | \u53D1\u5E03\u65F6\u95F4 |",
      "| --: | --- | --- | --- |"
    );
    videos.forEach((video, index) => {
      const rowTitle = escapeMdCell(video.title);
      const url = video.url;
      const published = formatPubdate(video.pubdate);
      lines.push(`| ${index + 1} | ${rowTitle} | ${url} | ${published} |`);
    });
    const content = lines.join("\n") + "\n";
    const parts = notePath.split("/");
    let currentPath = "";
    for (let i = 0; i < parts.length - 1; i++) {
      currentPath += (i === 0 ? "" : "/") + parts[i];
      const folder = this.vault.getAbstractFileByPath(currentPath);
      if (!folder) {
        await this.vault.createFolder(currentPath);
      }
    }
    const existingFile = this.vault.getAbstractFileByPath(notePath);
    if (existingFile instanceof import_obsidian2.TFile) {
      await this.vault.modify(existingFile, content);
    } else {
      await this.vault.create(notePath, content);
    }
  }
  async updateIndexNote(channels) {
    const lines = [
      "# B\u7AD9UP\u4E3B\u540C\u6B65\u7D22\u5F15",
      "",
      "| \u6807\u9898 | UP\u4E3B | \u6765\u6E90 | \u5206\u7C7B | \u89C6\u9891\u6570 | \u6700\u8FD1\u540C\u6B65 |",
      "| --- | --- | --- | --- | --- | --- |"
    ];
    channels.forEach((item) => {
      const title = escapeMdCell(item.title);
      const upName = escapeMdCell(item.up_name);
      const upUrl = item.source_url;
      const category = escapeMdCell(item.target_dir);
      const total = item.total_video_count;
      const synced = escapeMdCell(item.last_synced_at);
      lines.push(`| ${title} | ${upName} | [\u6253\u5F00](${upUrl}) | \`${category}\` | ${total} | ${synced} |`);
    });
    const content = lines.join("\n") + "\n";
    const parts = this.indexNoteName.split("/");
    let currentPath = "";
    for (let i = 0; i < parts.length - 1; i++) {
      currentPath += (i === 0 ? "" : "/") + parts[i];
      const folder = this.vault.getAbstractFileByPath(currentPath);
      if (!folder) {
        await this.vault.createFolder(currentPath);
      }
    }
    const existingFile = this.vault.getAbstractFileByPath(this.indexNoteName);
    if (existingFile instanceof import_obsidian2.TFile) {
      await this.vault.modify(existingFile, content);
    } else {
      await this.vault.create(this.indexNoteName, content);
    }
    return this.indexNoteName;
  }
};

// src/storage.ts
var StateStore = class {
  constructor() {
    this.storageKey = "bilibili-sync-state";
  }
  getData() {
    const data = localStorage.getItem(this.storageKey);
    if (!data) {
      return { sources: {}, videos: {} };
    }
    try {
      return JSON.parse(data);
    } catch (e) {
      return { sources: {}, videos: {} };
    }
  }
  setData(data) {
    localStorage.setItem(this.storageKey, JSON.stringify(data));
  }
  loadVideoMap(sourceKey) {
    const data = this.getData();
    const videos = data.videos[sourceKey] || [];
    const map = {};
    for (const video of videos) {
      map[video.bvid] = video;
    }
    return map;
  }
  upsertVideos(sourceKey, videos) {
    const data = this.getData();
    const existingVideos = data.videos[sourceKey] || [];
    const existingBvids = new Set(existingVideos.map((v) => v.bvid));
    let newCount = 0;
    for (const video of videos) {
      const existing = existingVideos.find((v) => v.bvid === video.bvid);
      if (existing) {
        existing.oid = video.oid;
        existing.title = video.title;
        existing.url = video.url;
        existing.pubdate = video.pubdate;
        existing.duration_seconds = video.duration_seconds;
        existing.view_count = video.view_count;
        existing.source_kind = video.source_kind;
      } else {
        existingVideos.push({
          ...video,
          created_at: (/* @__PURE__ */ new Date()).toISOString()
        });
        newCount++;
      }
    }
    data.videos[sourceKey] = existingVideos;
    this.setData(data);
    return newCount;
  }
  listVideos(sourceKey) {
    const data = this.getData();
    const videos = data.videos[sourceKey] || [];
    return videos.sort((a, b) => {
      const dateDiff = b.pubdate - a.pubdate;
      return dateDiff !== 0 ? dateDiff : b.bvid.localeCompare(a.bvid);
    });
  }
  upsertSource(source) {
    const data = this.getData();
    data.sources[source.source_key] = source;
    this.setData(data);
  }
  listSources() {
    const data = this.getData();
    return Object.values(data.sources).sort((a, b) => {
      const dateDiff = b.last_synced_at.localeCompare(a.last_synced_at);
      return dateDiff !== 0 ? dateDiff : a.title.localeCompare(b.title);
    });
  }
  getSource(sourceKey) {
    const data = this.getData();
    return data.sources[sourceKey] || null;
  }
  deleteSource(sourceKey) {
    const data = this.getData();
    delete data.sources[sourceKey];
    delete data.videos[sourceKey];
    this.setData(data);
  }
};

// src/sync-panel.ts
var import_obsidian4 = require("obsidian");

// src/components/tree-select.ts
var import_obsidian3 = require("obsidian");
var TreeSelectComponent = class {
  constructor(container, vault, excludedDirs = [], basePath = "", onSelectionChange = () => {
  }) {
    this.selectedPath = "";
    this.container = container;
    this.vault = vault;
    this.excludedDirs = excludedDirs;
    this.basePath = basePath;
    this.onSelectionChange = onSelectionChange;
    this.root = this.buildTree();
    this.render();
  }
  buildTree() {
    let rootFolder;
    if (this.basePath) {
      const baseFile = this.vault.getAbstractFileByPath(this.basePath);
      if (baseFile instanceof import_obsidian3.TFolder) {
        rootFolder = baseFile;
      } else {
        rootFolder = this.vault.getRoot();
      }
    } else {
      rootFolder = this.vault.getRoot();
    }
    return this.buildNode(rootFolder, "", true);
  }
  buildNode(folder, parentPath, isRoot = false) {
    const path = parentPath ? `${parentPath}/${folder.name}` : folder.name;
    const children = [];
    if (!isRoot && this.isExcluded(path)) {
      return null;
    }
    for (const child of folder.children) {
      if (child instanceof import_obsidian3.TFolder && !child.name.startsWith(".")) {
        const childNode = this.buildNode(child, isRoot ? "" : path);
        if (childNode) {
          children.push(childNode);
        }
      }
    }
    children.sort((a, b) => a.name.localeCompare(b.name));
    return {
      name: folder.name || "\u6839\u76EE\u5F55",
      path: isRoot ? "" : path || "",
      children,
      isExpanded: isRoot,
      // 默认展开第一层
      isSelected: false,
      isFolder: true
    };
  }
  isExcluded(path) {
    const fullPath = this.basePath ? `${this.basePath}/${path}` : path;
    return this.excludedDirs.some((excluded) => {
      if (!excluded)
        return false;
      const fullExcludedPath = this.basePath && !excluded.startsWith(this.basePath) ? `${this.basePath}/${excluded}` : excluded;
      return fullPath === fullExcludedPath || fullPath.startsWith(fullExcludedPath + "/") || fullPath === excluded || fullPath.startsWith(excluded + "/") || path === excluded || path.startsWith(excluded + "/");
    });
  }
  render() {
    this.container.empty();
    this.treeContainer = this.container.createEl("div", {
      cls: "tree-select-container"
    });
    this.renderNode(this.root, this.treeContainer, 0);
  }
  renderNode(node, container, level) {
    const nodeEl = container.createEl("div", {
      cls: `tree-node ${node.isSelected ? "tree-node-selected" : ""}`
    });
    const contentEl = nodeEl.createEl("div", {
      cls: "tree-node-content"
    });
    contentEl.createEl("span", {
      cls: "tree-node-indent",
      text: "  ".repeat(level)
    });
    if (node.children.length > 0) {
      const expandIcon = contentEl.createEl("span", {
        cls: `tree-node-expand-icon ${node.isExpanded ? "expanded" : ""}`,
        text: node.isExpanded ? "\u25BC" : "\u25B6"
      });
      expandIcon.addEventListener("click", (e) => {
        e.stopPropagation();
        node.isExpanded = !node.isExpanded;
        this.rerender();
      });
    } else {
      contentEl.createEl("span", {
        cls: "tree-node-expand-icon",
        text: "  "
      });
    }
    contentEl.createEl("span", {
      cls: "tree-node-icon",
      text: "\u{1F4C1}"
    });
    const nameEl = contentEl.createEl("span", {
      cls: "tree-node-name",
      text: node.name
    });
    contentEl.addEventListener("click", () => {
      this.selectNode(node);
    });
    if (node.isExpanded && node.children.length > 0) {
      const childrenEl = nodeEl.createEl("div", {
        cls: "tree-node-children"
      });
      for (const child of node.children) {
        this.renderNode(child, childrenEl, level + 1);
      }
    }
  }
  selectNode(node) {
    this.clearSelection(this.root);
    node.isSelected = true;
    this.selectedPath = node.path;
    this.rerender();
    const fullPath = this.basePath && node.path ? `${this.basePath}/${node.path}` : node.path;
    this.onSelectionChange(fullPath);
  }
  clearSelection(node) {
    node.isSelected = false;
    for (const child of node.children) {
      this.clearSelection(child);
    }
  }
  rerender() {
    this.render();
  }
  expandAll() {
    this.expandNode(this.root);
    this.rerender();
  }
  expandNode(node) {
    node.isExpanded = true;
    for (const child of node.children) {
      this.expandNode(child);
    }
  }
  collapseAll() {
    this.collapseNode(this.root);
    this.root.isExpanded = true;
    this.rerender();
  }
  collapseNode(node) {
    node.isExpanded = false;
    for (const child of node.children) {
      this.collapseNode(child);
    }
  }
  getSelectedPath() {
    return this.selectedPath;
  }
  setSelectedPath(path) {
    this.selectedPath = path;
    this.setSelectionByPath(this.root, path);
    this.rerender();
  }
  setSelectionByPath(node, path) {
    const relativePath = this.basePath && path.startsWith(this.basePath + "/") ? path.substring(this.basePath.length + 1) : path;
    if (node.path === relativePath) {
      node.isSelected = true;
      return true;
    }
    for (const child of node.children) {
      if (this.setSelectionByPath(child, path)) {
        node.isExpanded = true;
        return true;
      }
    }
    return false;
  }
  setExcludedDirs(excludedDirs) {
    this.excludedDirs = excludedDirs;
    this.root = this.buildTree();
    this.rerender();
  }
  setBasePath(basePath) {
    this.basePath = basePath;
    this.root = this.buildTree();
    this.rerender();
  }
};

// src/sync-panel.ts
var VIEW_TYPE_BILIBILI_SYNC = "bilibili-sync-view";
var SyncPanel = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentTab = "sync";
    this.treeSelect = null;
    this.urlInput = null;
    this.selectedPath = "";
    this.statusDiv = null;
    this.logDiv = null;
    this.pendingUrl = "";
    this.pendingDir = "";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_BILIBILI_SYNC;
  }
  getDisplayText() {
    return "B\u7AD9\u540C\u6B65";
  }
  getIcon() {
    return "video";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("bilibili-sync-panel");
    container.createEl("h2", { text: "B\u7AD9\u89C6\u9891\u540C\u6B65\u5230Obsidian" });
    const tabHeader = container.createEl("div", { cls: "tab-header" });
    const syncTabBtn = tabHeader.createEl("button", {
      text: "\u540C\u6B65",
      cls: `tab-button ${this.currentTab === "sync" ? "active" : ""}`
    });
    syncTabBtn.addEventListener("click", () => this.switchTab("sync"));
    const historyTabBtn = tabHeader.createEl("button", {
      text: "\u5386\u53F2",
      cls: `tab-button ${this.currentTab === "history" ? "active" : ""}`
    });
    historyTabBtn.addEventListener("click", () => this.switchTab("history"));
    const contentContainer = container.createEl("div", { cls: "tab-content" });
    if (this.currentTab === "sync") {
      this.renderSyncTab(contentContainer);
    } else {
      this.renderHistoryTab(contentContainer);
    }
  }
  switchTab(tab) {
    this.currentTab = tab;
    this.onOpen();
    if (tab === "sync" && (this.pendingUrl || this.pendingDir)) {
      setTimeout(() => {
        if (this.pendingUrl && this.urlInput) {
          this.urlInput.value = this.pendingUrl;
        }
        if (this.pendingDir && this.treeSelect) {
          this.selectedPath = this.pendingDir;
          this.treeSelect.setSelectedPath(this.pendingDir);
        }
        this.pendingUrl = "";
        this.pendingDir = "";
      }, 100);
    }
  }
  renderSyncTab(container) {
    const urlSection = container.createEl("div", { cls: "form-section" });
    urlSection.createEl("label", { text: "B\u7AD9\u94FE\u63A5", cls: "form-label" });
    this.urlInput = urlSection.createEl("input", {
      type: "text",
      placeholder: "\u8F93\u5165UP\u4E3B\u4E3B\u9875\u3001\u6295\u7A3F\u9875\u6216\u89C6\u9891\u94FE\u63A5",
      cls: "form-input"
    });
    const dirSection = container.createEl("div", { cls: "form-section" });
    dirSection.createEl("label", { text: "\u76EE\u6807\u5206\u7C7B\u76EE\u5F55", cls: "form-label" });
    const buttonGroup = dirSection.createEl("div", { cls: "tree-button-group" });
    buttonGroup.createEl("button", { text: "\u5168\u90E8\u5C55\u5F00" }).addEventListener("click", () => {
      if (this.treeSelect) {
        this.treeSelect.expandAll();
      }
    });
    buttonGroup.createEl("button", { text: "\u5168\u90E8\u6298\u53E0" }).addEventListener("click", () => {
      if (this.treeSelect) {
        this.treeSelect.collapseAll();
      }
    });
    const treeContainer = dirSection.createEl("div", { cls: "tree-select-wrapper" });
    const basePath = this.plugin.settings.syncRoot || "";
    this.treeSelect = new TreeSelectComponent(
      treeContainer,
      this.app.vault,
      this.plugin.settings.excludedDirs,
      basePath,
      (path) => {
        this.selectedPath = path;
      }
    );
    this.statusDiv = container.createEl("div", { text: "\u51C6\u5907\u5C31\u7EEA" });
    this.statusDiv.addClass("bilibili-sync-status");
    this.logDiv = container.createEl("div");
    this.logDiv.addClass("bilibili-sync-log");
    const buttonDiv = container.createEl("div", { cls: "sync-button-group" });
    buttonDiv.createEl("button", { text: "\u5F00\u59CB\u540C\u6B65", cls: "mod-cta" }).addEventListener("click", () => this.startSync());
    buttonDiv.createEl("button", { text: "\u6E05\u7A7A\u65E5\u5FD7" }).addEventListener("click", () => {
      if (this.logDiv) {
        this.logDiv.empty();
      }
    });
  }
  appendLog(message) {
    if (!this.logDiv)
      return;
    const timestamp = (/* @__PURE__ */ new Date()).toTimeString().split(" ")[0];
    this.logDiv.createEl("div", { text: `[${timestamp}] ${message}` });
    this.logDiv.scrollTop = this.logDiv.scrollHeight;
  }
  renderHistoryTab(container) {
    const sources = this.plugin.store.listSources();
    if (sources.length === 0) {
      container.createEl("div", { text: "\u6682\u65E0\u540C\u6B65\u8BB0\u5F55", cls: "history-empty" });
      return;
    }
    const historyList = container.createEl("div", { cls: "history-list" });
    for (const source of sources) {
      this.renderHistoryItem(historyList, source);
    }
  }
  renderHistoryItem(container, source) {
    const item = container.createEl("div", { cls: "history-item" });
    const header = item.createEl("div", { cls: "history-item-header" });
    const typeLabel = source.source_type === "up" ? "UP\u4E3B" : source.source_type === "season" ? "\u5408\u96C6" : "\u7CFB\u5217";
    header.createEl("span", {
      text: typeLabel,
      cls: `history-item-type type-${source.source_type}`
    });
    header.createEl("span", {
      text: source.title,
      cls: "history-item-title"
    });
    const expandIcon = header.createEl("span", {
      text: "\u25B6",
      cls: "history-item-expand-icon"
    });
    const details = item.createEl("div", { cls: "history-item-details hidden" });
    details.createEl("div", {
      text: `URL: ${source.source_url}`,
      cls: "history-item-url"
    });
    details.createEl("div", {
      text: `\u6700\u8FD1\u540C\u6B65: ${source.last_synced_at}`,
      cls: "history-item-time"
    });
    details.createEl("div", {
      text: `\u89C6\u9891\u6570: ${source.total_video_count}`,
      cls: "history-item-count"
    });
    const buttonDiv = details.createEl("div", { cls: "history-item-buttons" });
    buttonDiv.createEl("button", { text: "\u589E\u91CF\u540C\u6B65" }).addEventListener("click", async () => {
      this.pendingUrl = source.source_url;
      this.pendingDir = source.target_dir;
      this.switchTab("sync");
    });
    buttonDiv.createEl("button", { text: "\u6253\u5F00\u7B14\u8BB0" }).addEventListener("click", async () => {
      const noteFile = this.app.vault.getAbstractFileByPath(source.note_path);
      if (noteFile instanceof import_obsidian4.TFile) {
        await this.app.workspace.openLinkText(source.note_path, "", true);
      }
    });
    buttonDiv.createEl("button", { text: "\u5220\u9664", cls: "mod-warning" }).addEventListener("click", () => {
      if (confirm(`\u786E\u5B9A\u8981\u5220\u9664 ${source.title} \u7684\u540C\u6B65\u8BB0\u5F55\u5417\uFF1F`)) {
        this.plugin.store.deleteSource(source.source_key);
        item.remove();
      }
    });
    header.addEventListener("click", () => {
      details.classList.toggle("hidden");
      expandIcon.textContent = details.classList.contains("hidden") ? "\u25B6" : "\u25BC";
    });
  }
  async startSync() {
    if (!this.urlInput || !this.statusDiv)
      return;
    const url = this.urlInput.value.trim();
    if (!url) {
      new import_obsidian4.Notice("\u8BF7\u8F93\u5165B\u7AD9\u94FE\u63A5");
      return;
    }
    const categoryPath = this.selectedPath;
    if (!categoryPath) {
      new import_obsidian4.Notice("\u8BF7\u9009\u62E9\u76EE\u6807\u5206\u7C7B\u76EE\u5F55");
      return;
    }
    this.statusDiv.setText("\u6267\u884C\u4E2D...");
    this.urlInput.disabled = true;
    try {
      this.appendLog(`\u5F00\u59CB\u5904\u7406\uFF1A${url}`);
      const result = await this.plugin.importUrl(url, categoryPath, (message) => {
        this.appendLog(message);
      });
      if (this.statusDiv) {
        this.statusDiv.setText("\u5B8C\u6210");
      }
      this.appendLog(`\u5B8C\u6210\uFF1A${result.up_name}\uFF0C\u65B0\u589E ${result.new_count} \u4E2A\uFF0C\u7D2F\u8BA1 ${result.total_count} \u4E2A\u3002`);
      this.appendLog(`\u7B14\u8BB0\uFF1A${result.note_path}`);
      if (this.plugin.settings.enableIndexNote) {
        this.appendLog(`\u7D22\u5F15\uFF1A${result.index_path}`);
      }
      new import_obsidian4.Notice(`\u540C\u6B65\u5B8C\u6210\uFF1A${result.up_name}
\u65B0\u589E ${result.new_count} \u4E2A\u89C6\u9891`);
      const noteFile = this.app.vault.getAbstractFileByPath(result.note_path);
      if (noteFile instanceof import_obsidian4.TFile) {
        await this.app.workspace.openLinkText(result.note_path, "", true);
      }
    } catch (error) {
      if (this.statusDiv) {
        this.statusDiv.setText("\u5931\u8D25");
      }
      this.appendLog(`\u5931\u8D25\uFF1A${error.message}`);
      new import_obsidian4.Notice(`\u540C\u6B65\u5931\u8D25\uFF1A${error.message}`);
    } finally {
      if (this.urlInput) {
        this.urlInput.disabled = false;
      }
    }
  }
  async onClose() {
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  enableIndexNote: true,
  indexNoteName: "B\u7AD9UP\u4E3B\u540C\u6B65\u7D22\u5F15.md",
  syncRoot: "",
  excludedDirs: []
};
var BilibiliSyncPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.client = new BilibiliClient();
    this.store = new StateStore();
    this.registerView(
      VIEW_TYPE_BILIBILI_SYNC,
      (leaf) => new SyncPanel(leaf, this)
    );
    const ribbonIconEl = this.addRibbonIcon("video", "B\u7AD9\u540C\u6B65", (evt) => {
      this.activateView();
    });
    ribbonIconEl.setAttribute("aria-label", "B\u7AD9\u540C\u6B65");
    ribbonIconEl.addEventListener("contextmenu", (evt) => {
      const menu = new import_obsidian5.Menu();
      menu.addItem((item) => {
        item.setTitle("\u6253\u5F00\u540C\u6B65\u9762\u677F").onClick(() => {
          this.activateView();
        });
      });
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("\u63D2\u4EF6\u8BBE\u7F6E").onClick(() => {
          this.openSettings();
        });
      });
      menu.showAtMouseEvent(evt);
    });
    this.addCommand({
      id: "sync-bilibili-url",
      name: "\u540C\u6B65B\u7AD9\u94FE\u63A5",
      callback: () => this.openSyncModal()
    });
    this.addCommand({
      id: "view-sync-history",
      name: "\u67E5\u770B\u540C\u6B65\u5386\u53F2",
      callback: () => this.openHistoryModal()
    });
    this.addCommand({
      id: "open-sync-panel",
      name: "\u6253\u5F00\u540C\u6B65\u9762\u677F",
      callback: () => this.activateView()
    });
    this.addSettingTab(new BilibiliSyncSettingTab(this.app, this));
    const statusBarItem = this.addStatusBarItem();
    statusBarItem.setText("B\u7AD9\u540C\u6B65");
    statusBarItem.setAttribute("aria-label", "\u70B9\u51FB\u540C\u6B65B\u7AD9\u94FE\u63A5");
    statusBarItem.addEventListener("click", () => this.activateView());
    console.log("Bilibili to Obsidian plugin loaded");
  }
  onunload() {
    console.log("Bilibili to Obsidian plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async openSyncModal() {
    const modal = new BilibiliSyncModal(this.app, this);
    modal.open();
  }
  async openHistoryModal() {
    const modal = new HistoryModal(this.app, this);
    modal.open();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_BILIBILI_SYNC);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({
          type: VIEW_TYPE_BILIBILI_SYNC,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  openSettings() {
    this.app.setting.open();
    this.app.setting.openTabById(this.manifest.id);
  }
  async importUrl(url, categoryRel, progressCallback) {
    const progress = progressCallback || (() => {
    });
    progress("\u89E3\u6790\u94FE\u63A5...");
    const target = await this.client.resolveTarget(url);
    progress(`\u8BC6\u522B\u5230\u76EE\u6807\uFF1A${target.title} [${target.source_type}]`);
    progress("\u6293\u53D6\u89C6\u9891\u5217\u8868...");
    const { target: updatedTarget, videos, collections } = await this.client.fetchTargetVideos(target);
    progress(`\u6293\u53D6\u5B8C\u6210\uFF1A\u5171\u8BC6\u522B ${videos.length} \u4E2A\u89C6\u9891\u3002`);
    const existingMap = this.store.loadVideoMap(updatedTarget.source_key);
    const newVideos = videos.filter((video) => !existingMap[video.bvid]);
    progress(`\u589E\u91CF\u5BF9\u6BD4\u5B8C\u6210\uFF1A\u65B0\u589E ${newVideos.length} \u4E2A\uFF0C\u5DF2\u5B58\u5728 ${Object.keys(existingMap).length} \u4E2A\u3002`);
    this.store.upsertVideos(updatedTarget.source_key, videos);
    const allVideos = this.store.listVideos(updatedTarget.source_key);
    const writer = new ObsidianWriter(this.app.vault, this.getIndexNotePath());
    const notePath = writer.notePathFor(
      updatedTarget.source_type,
      updatedTarget.title,
      updatedTarget.source_id,
      categoryRel
    );
    progress("\u5199\u5165 Obsidian \u7B14\u8BB0...");
    await writer.writeChannelNote(
      notePath,
      updatedTarget.title,
      updatedTarget.up_name,
      updatedTarget.mid,
      updatedTarget.source_url,
      allVideos,
      collections,
      categoryRel,
      updatedTarget.source_type
    );
    const syncedAt = (/* @__PURE__ */ new Date()).toISOString().replace("T", " ").substring(0, 19);
    this.store.upsertSource({
      source_key: updatedTarget.source_key,
      source_type: updatedTarget.source_type,
      source_id: updatedTarget.source_id,
      mid: updatedTarget.mid,
      title: updatedTarget.title,
      up_name: updatedTarget.up_name,
      source_url: updatedTarget.source_url,
      target_dir: categoryRel,
      note_path: notePath,
      collections_json: JSON.stringify(collections),
      last_synced_at: syncedAt,
      total_video_count: allVideos.length
    });
    let index_path = "";
    if (this.settings.enableIndexNote) {
      index_path = await writer.updateIndexNote(this.store.listSources());
      progress("\u540C\u6B65\u7D22\u5F15\u5B8C\u6210\u3002");
    } else {
      progress("\u8DF3\u8FC7\u7D22\u5F15\u6587\u4EF6\uFF08\u5DF2\u7981\u7528\uFF09\u3002");
    }
    return {
      mid: updatedTarget.mid,
      up_name: updatedTarget.up_name,
      up_url: updatedTarget.source_url,
      title: updatedTarget.title,
      source_type: updatedTarget.source_type,
      note_path: notePath,
      index_path,
      new_count: newVideos.length,
      total_count: allVideos.length,
      collections
    };
  }
  getIndexNotePath() {
    if (!this.settings.enableIndexNote) {
      return "";
    }
    const syncRoot = this.settings.syncRoot;
    if (syncRoot) {
      return `${syncRoot}/${this.settings.indexNoteName}`;
    }
    return this.settings.indexNoteName;
  }
};
var BilibiliSyncModal = class extends import_obsidian5.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("bilibili-sync-modal");
    contentEl.createEl("h2", { text: "B\u7AD9\u89C6\u9891\u540C\u6B65\u5230Obsidian" });
    contentEl.createEl("label", { text: "B\u7AD9\u94FE\u63A5" });
    this.urlInput = contentEl.createEl("input", {
      type: "text",
      placeholder: "\u8F93\u5165UP\u4E3B\u4E3B\u9875\u3001\u6295\u7A3F\u9875\u6216\u89C6\u9891\u94FE\u63A5"
    });
    contentEl.createEl("label", { text: "\u76EE\u6807\u5206\u7C7B\u76EE\u5F55" });
    this.categorySelect = contentEl.createEl("select");
    this.addExistingDirectories();
    this.statusDiv = contentEl.createEl("div", { text: "\u51C6\u5907\u5C31\u7EEA" });
    this.statusDiv.addClass("bilibili-sync-status");
    this.logDiv = contentEl.createEl("div");
    this.logDiv.addClass("bilibili-sync-log");
    const buttonDiv = contentEl.createEl("div");
    buttonDiv.createEl("button", { text: "\u5F00\u59CB\u540C\u6B65" }).addEventListener("click", () => this.startSync());
    buttonDiv.createEl("button", { text: "\u53D6\u6D88" }).addEventListener("click", () => this.close());
  }
  async addExistingDirectories() {
    const vault = this.app.vault;
    const syncRoot = this.plugin.settings.syncRoot;
    let root;
    if (syncRoot) {
      const baseFile = vault.getAbstractFileByPath(syncRoot);
      if (baseFile instanceof import_obsidian5.TFolder) {
        root = baseFile;
      } else {
        root = vault.getRoot();
      }
    } else {
      root = vault.getRoot();
    }
    const addFolders = (folder, prefix = "") => {
      for (const child of folder.children) {
        if (child instanceof import_obsidian5.TFolder && !child.name.startsWith(".")) {
          const path = prefix ? `${prefix}/${child.name}` : child.name;
          this.categorySelect.createEl("option", {
            text: path,
            value: path
          });
          addFolders(child, path);
        }
      }
    };
    addFolders(root);
  }
  appendLog(message) {
    const timestamp = (/* @__PURE__ */ new Date()).toTimeString().split(" ")[0];
    this.logDiv.createEl("div", { text: `[${timestamp}] ${message}` });
    this.logDiv.scrollTop = this.logDiv.scrollHeight;
  }
  async startSync() {
    const url = this.urlInput.value.trim();
    if (!url) {
      new import_obsidian5.Notice("\u8BF7\u8F93\u5165B\u7AD9\u94FE\u63A5");
      return;
    }
    const categoryPath = this.categorySelect.value;
    if (!categoryPath) {
      new import_obsidian5.Notice("\u8BF7\u9009\u62E9\u76EE\u6807\u5206\u7C7B\u76EE\u5F55");
      return;
    }
    this.statusDiv.setText("\u6267\u884C\u4E2D...");
    this.urlInput.disabled = true;
    this.categorySelect.disabled = true;
    try {
      this.appendLog(`\u5F00\u59CB\u5904\u7406\uFF1A${url}`);
      const result = await this.plugin.importUrl(url, categoryPath, (message) => {
        this.appendLog(message);
      });
      this.statusDiv.setText("\u5B8C\u6210");
      this.appendLog(`\u5B8C\u6210\uFF1A${result.up_name}\uFF0C\u65B0\u589E ${result.new_count} \u4E2A\uFF0C\u7D2F\u8BA1 ${result.total_count} \u4E2A\u3002`);
      this.appendLog(`\u7B14\u8BB0\uFF1A${result.note_path}`);
      if (this.plugin.settings.enableIndexNote) {
        this.appendLog(`\u7D22\u5F15\uFF1A${result.index_path}`);
      }
      new import_obsidian5.Notice(`\u540C\u6B65\u5B8C\u6210\uFF1A${result.up_name}
\u65B0\u589E ${result.new_count} \u4E2A\u89C6\u9891`);
      const noteFile = this.app.vault.getAbstractFileByPath(result.note_path);
      if (noteFile instanceof import_obsidian5.TFile) {
        await this.app.workspace.openLinkText(result.note_path, "", true);
      }
    } catch (error) {
      this.statusDiv.setText("\u5931\u8D25");
      this.appendLog(`\u5931\u8D25\uFF1A${error.message}`);
      new import_obsidian5.Notice(`\u540C\u6B65\u5931\u8D25\uFF1A${error.message}`);
    } finally {
      this.urlInput.disabled = false;
      this.categorySelect.disabled = false;
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var HistoryModal = class extends import_obsidian5.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("bilibili-sync-modal");
    contentEl.createEl("h2", { text: "\u540C\u6B65\u5386\u53F2" });
    this.historyList = contentEl.createEl("div");
    const sources = this.plugin.store.listSources();
    if (sources.length === 0) {
      this.historyList.createEl("div", { text: "\u6682\u65E0\u540C\u6B65\u8BB0\u5F55" });
      return;
    }
    for (const source of sources) {
      const item = this.historyList.createEl("div");
      item.createEl("div", { text: source.title }).addClass("bilibili-sync-history-title");
      item.createEl("div", { text: `\u7C7B\u578B\uFF1A${source.source_type}` });
      item.createEl("div", { text: `\u6700\u8FD1\u540C\u6B65\uFF1A${source.last_synced_at}` });
      item.createEl("div", { text: `\u89C6\u9891\u6570\uFF1A${source.total_video_count}` });
      const buttonDiv = item.createEl("div");
      buttonDiv.createEl("button", { text: "\u91CD\u65B0\u540C\u6B65" }).addEventListener("click", async () => {
        const modal = new BilibiliSyncModal(this.app, this.plugin);
        modal.urlInput.value = source.source_url;
        modal.open();
        this.close();
      });
      buttonDiv.createEl("button", { text: "\u6253\u5F00\u7B14\u8BB0" }).addEventListener("click", async () => {
        const noteFile = this.app.vault.getAbstractFileByPath(source.note_path);
        if (noteFile instanceof import_obsidian5.TFile) {
          await this.app.workspace.openLinkText(source.note_path, "", true);
          this.close();
        }
      });
      buttonDiv.createEl("button", { text: "\u5220\u9664\u8BB0\u5F55" }).addEventListener("click", () => {
        if (confirm(`\u786E\u5B9A\u8981\u5220\u9664 ${source.title} \u7684\u540C\u6B65\u8BB0\u5F55\u5417\uFF1F`)) {
          this.plugin.store.deleteSource(source.source_key);
          item.remove();
          new import_obsidian5.Notice(`\u5DF2\u5220\u9664 ${source.title} \u7684\u540C\u6B65\u8BB0\u5F55`);
        }
      });
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var BilibiliSyncSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "B\u7AD9\u540C\u6B65\u8BBE\u7F6E" });
    new import_obsidian5.Setting(containerEl).setName("\u542F\u7528\u7D22\u5F15\u6587\u4EF6").setDesc("\u662F\u5426\u751F\u6210\u7D22\u5F15\u6587\u4EF6\u8BB0\u5F55\u6240\u6709\u540C\u6B65\u7684UP\u4E3B").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableIndexNote).onChange(async (value) => {
      this.plugin.settings.enableIndexNote = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.enableIndexNote) {
      new import_obsidian5.Setting(containerEl).setName("\u7D22\u5F15\u6587\u4EF6\u540D\u79F0").setDesc("\u7D22\u5F15\u6587\u4EF6\u7684\u540D\u79F0\uFF08\u4E0D\u542B\u8DEF\u5F84\uFF09").addText((text) => text.setPlaceholder("B\u7AD9UP\u4E3B\u540C\u6B65\u7D22\u5F15.md").setValue(this.plugin.settings.indexNoteName).onChange(async (value) => {
        this.plugin.settings.indexNoteName = value;
        await this.plugin.saveSettings();
      }));
    }
    const syncRootSetting = new import_obsidian5.Setting(containerEl).setName("\u540C\u6B65\u6839\u76EE\u5F55").setDesc("\u76EE\u5F55\u9009\u62E9\u5668\u7684\u6839\u8DEF\u5F84\uFF0C\u7559\u7A7A\u8868\u793A\u6574\u4E2A\u4FDD\u9669\u5E93");
    const syncRootSelect = syncRootSetting.controlEl.createEl("select");
    syncRootSelect.createEl("option", { text: "\u6574\u4E2A\u4FDD\u9669\u5E93\uFF08\u6839\u76EE\u5F55\uFF09", value: "" });
    this.addFolderOptions(syncRootSelect, "");
    syncRootSelect.value = this.plugin.settings.syncRoot;
    syncRootSelect.addEventListener("change", async () => {
      this.plugin.settings.syncRoot = syncRootSelect.value;
      await this.plugin.saveSettings();
      this.refreshSyncPanel();
    });
    containerEl.createEl("h3", { text: "\u6392\u9664\u76EE\u5F55" });
    containerEl.createEl("p", {
      text: "\u4EE5\u4E0B\u76EE\u5F55\u5C06\u4E0D\u4F1A\u5728\u76EE\u6807\u76EE\u5F55\u9009\u62E9\u5668\u4E2D\u663E\u793A\uFF08\u57FA\u4E8E\u540C\u6B65\u6839\u76EE\u5F55\uFF09\u3002",
      cls: "setting-item-description"
    });
    const excludedDiv = containerEl.createEl("div");
    this.plugin.settings.excludedDirs.forEach((dir, index) => {
      const dirDiv = excludedDiv.createEl("div");
      dirDiv.addClass("bilibili-sync-excluded-item");
      const dirSetting = new import_obsidian5.Setting(dirDiv).setName(`\u76EE\u5F55 ${index + 1}`);
      const cascader = dirSetting.controlEl.createEl("div", { cls: "cascader-select" });
      this.createCascadingSelect(cascader, dir, async (newPath) => {
        this.plugin.settings.excludedDirs[index] = newPath;
        await this.plugin.saveSettings();
      }, this.plugin.settings.syncRoot);
      dirSetting.addButton((button) => button.setButtonText("\u5220\u9664").setWarning().onClick(async () => {
        this.plugin.settings.excludedDirs.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
    });
    new import_obsidian5.Setting(containerEl).setName("\u6DFB\u52A0\u6392\u9664\u76EE\u5F55").setDesc("\u6DFB\u52A0\u8981\u6392\u9664\u7684\u76EE\u5F55\u8DEF\u5F84").addButton((button) => button.setButtonText("\u6DFB\u52A0").onClick(async () => {
      this.plugin.settings.excludedDirs.push("");
      await this.plugin.saveSettings();
      this.display();
    }));
  }
  addFolderOptions(select, basePath) {
    const vault = this.app.vault;
    const root = basePath ? vault.getAbstractFileByPath(basePath) : vault.getRoot();
    if (root instanceof import_obsidian5.TFolder) {
      const addFolders = (folder, prefix) => {
        for (const child of folder.children) {
          if (child instanceof import_obsidian5.TFolder && !child.name.startsWith(".")) {
            const path = prefix ? `${prefix}/${child.name}` : child.name;
            select.createEl("option", { text: path, value: path });
            addFolders(child, path);
          }
        }
      };
      addFolders(root, basePath);
    }
  }
  createCascadingSelect(container, initialPath, onChange, basePath = "") {
    container.empty();
    container.addClass("cascader-container");
    const vault = this.app.vault;
    const root = basePath ? vault.getAbstractFileByPath(basePath) : vault.getRoot();
    if (!(root instanceof import_obsidian5.TFolder))
      return;
    const pathParts = initialPath ? initialPath.split("/") : [];
    const selects = [];
    const selectElements = [];
    const createLevel = (parentPath, level, selectedPart = "") => {
      const selectWrapper = container.createEl("div", { cls: "cascader-level" });
      const select = selectWrapper.createEl("select", { cls: "cascader-select-item" });
      select.createEl("option", { text: "\u8BF7\u9009\u62E9...", value: "" });
      let parentFolder = null;
      if (parentPath) {
        const file = vault.getAbstractFileByPath(parentPath);
        if (file instanceof import_obsidian5.TFolder) {
          parentFolder = file;
        }
      } else {
        parentFolder = root;
      }
      if (parentFolder) {
        for (const child of parentFolder.children) {
          if (child instanceof import_obsidian5.TFolder && !child.name.startsWith(".")) {
            select.createEl("option", { text: child.name, value: child.name });
          }
        }
      }
      if (selectedPart) {
        select.value = selectedPart;
      }
      selects.push(select);
      selectElements.push(selectWrapper);
      select.addEventListener("change", () => {
        var _a;
        while (selects.length > level + 1) {
          selects.pop();
          (_a = selectElements.pop()) == null ? void 0 : _a.remove();
        }
        const currentPath = this.buildPath(selects);
        if (select.value) {
          const nextPath = currentPath;
          createLevel(nextPath, level + 1);
        }
        onChange(currentPath);
      });
      return select;
    };
    createLevel(basePath, 0, pathParts[0] || "");
    if (pathParts.length > 1) {
      let currentPath = pathParts[0] || "";
      for (let i = 1; i < pathParts.length; i++) {
        const level = i;
        createLevel(currentPath, level, pathParts[i] || "");
        currentPath = currentPath ? `${currentPath}/${pathParts[i]}` : pathParts[i];
      }
    }
  }
  buildPath(selects) {
    const parts = [];
    for (const select of selects) {
      if (select.value) {
        parts.push(select.value);
      } else {
        break;
      }
    }
    return parts.join("/");
  }
  refreshSyncPanel() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_BILIBILI_SYNC);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && view.onOpen) {
        view.onOpen();
      }
    }
  }
};
